name: tools-sync

on: 
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync-tools-docs: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Pull tools docs
      run: npm run docs:tools:sync

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v11.9

    - name: Create Pull Request
      if: steps.changed-files.any_changed
      uses: peter-evans/create-pull-request@v3
      with: 
        draft: false
        branch: tools-docs-sync
        delete-branch: true
        title: Update Tools Documentation
        body: Update changes from ERC725.js and LSP-Factory repositories 
